# Methods of Analysis

Periods with different air traffic volumes will be identified, and an initial capacity threshold will categorise periods of high, medium and low traffic volumes. We will assume that the daily capacity does not change, and there are no significant variations of traffic volumes throughout the different days of the week.

We will be using two different methods of computational analysis to answer the research question, combining two datasets of total air traffic flow and weather information:

##Regression and Correlation {-}
Using these methods of analysis, we can test the relationship between weather and traffic flows. An initial testing of how weather affects traffic flows into Changi via a visualisation of the regression model could provide us with information on which weather variables best explains changes to air traffic flows in Changi. 

##Multidimensional Scaling (MDS) & Factor Analysis {-}
In non-metric MDS, different variables that consists weather – rainfall, temperature, visibility and wind speeds, could be tested against total air traffic flow. The smaller the distances between the variables and high/low traffic flow outputs, the higher the chances that the specific component of weather heavily influences the occurrence of an air traffic congestion. 
In addition, a factor analysis will be performed on the dataset to determine which variables affect the traffic flow in Changi the most. 

##Cluster Analysis {-}

A cluster analysis on the dataset will be used to visualise any evidences of data clustering on the dimension reduction factor analysis already performed in the earlier sections. Through clustering, we can see patterns in our datapoints which could allude to a similarity in conditions affecting air traffic flow.




