# Multiple Regression

```{r message = FALSE}
library(tidyverse)
library(readxl)
library(lubridate)
library(ggplot2)
library(factoextra)
```



```{r include=FALSE}
library(tidyverse)
library(readxl)
library(lubridate)
library(ggplot2)
library(factoextra)
library(broom)
```

```{r include=FALSE}
#Weather data - July 2018 to February 2019 (daily summaries)
changi_daily_weather <- read_excel(here::here("Data/daily_weather_changi.xlsx")) %>% 
  mutate(date=date(date))

# Changi traffic data - Julu 2018 to February 2019 (hourly data)
changi_stats <- read_excel(here::here("Data/changi_stats.xlsx")) %>% 
  mutate(date = date(local_time))


#summary of daily sum of, and total departures and arrivals per day 

tfc_flow<-changi_stats %>% 
  group_by(date) %>% 
  summarise(arrival_tfc = sum(arrival_tfc),
            departure_tfc = sum(departure_tfc)) %>% 
  mutate(daily_tfc = departure_tfc+ arrival_tfc) %>% 
  mutate(mean_hourly_tfc = daily_tfc/24)
daily_stats_weather<-left_join(tfc_flow, changi_daily_weather)

```



```{r include=FALSE}
changi_hourly_weather<-read_excel(here::here("Data/weather_june18_feb19.xlsx")) 

changi_hourly_weather <-changi_hourly_weather %>% 
  mutate(date = date(local_time))

combined_data<- left_join(changi_hourly_weather, changi_stats) %>% 
  mutate(date=date(local_time))

rainy_days <- daily_stats_weather %>% 
  filter(daily_rainfall_mm>0) 

rainy_date<-rainy_days %>% 
  select(date)
```



```{r include=FALSE}

#combining daily traffic data and weather summaries
daily_stats_weather<-left_join(tfc_flow, changi_daily_weather)


#To check if our hypothesis that weather affects air traffic flows is true, we look at days when there is some rain in Changi
rainy_days <- daily_stats_weather %>% 
  filter(daily_rainfall_mm>0) # filtering out dates when changi experiences some rainfall
#Out of 243 days, 113 days had some rain in Changi - that's almost half

rainy_date<-rainy_days %>% 
  select(date) #filtering out the date component to join after performing MDS.
```


```{r}
cluster_data<-rainy_days %>% 
  select(date,daily_rainfall_mm, temp_mean_daily, daily_tfc, mean_hourly_tfc)

cluster_data<-cluster_data %>% 
  column_to_rownames(var = "date")
```




```{r}
rain<-cluster_data
ols_rain <- lm(daily_tfc ~ daily_rainfall_mm +`30min_rainfall_mm` + max_wind_speed + `120min_rainfall_mm` + wind_speed + temp_mean_daily + mean_hourly_tfc, daily_stats_weather)

glance(ols_rain)

tidy(ols_rain)
```




```{r}
#Traffic per hour >50 (in anticipation of further regressive analysis that could be done --> checking which hours have peak traffic movements)
tfc_gt_50<-changi_stats %>% 
  mutate(hourly_tfc = arrival_tfc + departure_tfc) %>% 
  filter(hourly_tfc >59) %>% 
  mutate(hour = hour(local_time))

tfc_gt_50 %>% 
  ggplot(aes(x = hour, y = hourly_tfc)) + geom_col(aes(fill = date))

summary(tfc_gt_50)
```
